version: '3.3'

#volumes:
#   pgdata:

services:
  database:
    image: 'postgres:15-alpine'
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
#      - ./db-data/:/var/lib/postgresql/data/
#      - pgdata:/var/lib/postgresql/data/
      - ./src/main/resources/sql/:/docker-entrypoint-initdb.d/
