version: '3.3'

#volumes:
#   dbdata:

services:
  database:
    image: 'postgres:15-alpine'
    ports:
      - "5432:5432"
    env_file:
      - .env
#    volumes:
#      - dbdata:/var/lib/postgresql/data:Z
